services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: firecode-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: firecode
    volumes:
      - mongodb_data:/data/db
    networks:
      - firecode-network

  # Backend Server
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: firecode-server
    restart: unless-stopped
    ports:
      - "80:80"
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongodb:27017/firecode
      - ACCESS_TOKEN_SECRET=your-secret-key-change-this-in-production
    volumes:
      - ./server:/app
      - /app/node_modules
    depends_on:
      - mongodb
    networks:
      - firecode-network

  # Frontend Client
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: firecode-client
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:80
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - server
    networks:
      - firecode-network
    stdin_open: true
    tty: true

volumes:
  mongodb_data:

networks:
  firecode-network:
    driver: bridge